//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.Usertype
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureSummary
    {
        public int LectureSummaryID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime LectureDate { get; set; }
        public string Description { get; set; }
        public string Suggestions { get; set; }
        public string Breakdown { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
