//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.Usertype
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureReview
    {
        public int LectureReviewID { get; set; }
        public int EventID { get; set; }
        public int PersonID { get; set; }
        public string Comment { get; set; }
        public string Rating { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual Student Student { get; set; }
    }
}
