//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.Usertype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.LectureReviews = new HashSet<LectureReview>();
            this.Milestones = new HashSet<Milestone>();
        }
    
        public int PersonID { get; set; }
        public int StudentNumber { get; set; }
        public bool Graduate { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> YearOfStudy { get; set; }
        public Nullable<int> Residence { get; set; }
        public Nullable<int> StudentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureReview> LectureReviews { get; set; }
        public virtual Person Person { get; set; }
        public virtual Residence Residence1 { get; set; }
        public virtual StudentType StudentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestone> Milestones { get; set; }
    }
}
