//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.Usertype
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_TRWLA_StagingEntities : DbContext
    {
        public Db_TRWLA_StagingEntities()
            : base("name=Db_TRWLA_StagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Alumnus> Alumni { get; set; }
        public virtual DbSet<CommEngage> CommEngages { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FunctionEvent> FunctionEvents { get; set; }
        public virtual DbSet<GuestSpeaker> GuestSpeakers { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<LectureReview> LectureReviews { get; set; }
        public virtual DbSet<LectureSummary> LectureSummaries { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Milestone> Milestones { get; set; }
        public virtual DbSet<MilestoneType> MilestoneTypes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Residence> Residences { get; set; }
        public virtual DbSet<ResType> ResTypes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SecurityAnswer> SecurityAnswers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentType> StudentTypes { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<VenueType> VenueTypes { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<VolunteerFeedback> VolunteerFeedbacks { get; set; }
        public virtual DbSet<VolunteerType> VolunteerTypes { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
    }
}
