//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.Usertype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volunteer()
        {
            this.LectureSummaries = new HashSet<LectureSummary>();
            this.VolunteerFeedbacks = new HashSet<VolunteerFeedback>();
        }
    
        public int PersonID { get; set; }
        public Nullable<int> VolunteerType { get; set; }
        public Nullable<int> Residence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureSummary> LectureSummaries { get; set; }
        public virtual Person Person { get; set; }
        public virtual Residence Residence1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerFeedback> VolunteerFeedbacks { get; set; }
        public virtual VolunteerType VolunteerType1 { get; set; }
    }
}
