//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageUpload
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImageAlt { get; set; }
        public byte[] ImageData { get; set; }
        public string ContentType { get; set; }
        public bool Approved { get; set; }
    }
}
