//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureReview
    {
        public int reviewID { get; set; }
        public string Review { get; set; }
        public int RatingID { get; set; }
        public int StudentID { get; set; }
        public int LectureID { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual RatingType RatingType { get; set; }
        public virtual Student Student { get; set; }
    }
}
