//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int VolunteerID { get; set; }
        public string Volunteer_Name { get; set; }
        public string Volunteer_Surname { get; set; }
        public string Volunteer_Phone { get; set; }
        public System.DateTime Volunteer_DoB { get; set; }
        public string ActiveStatus { get; set; }
        public string VolId { get; set; }
        public int UserTypeID { get; set; }
        public int VolunteerTypeID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual VolunteerType VolunteerType { get; set; }
    }
}
