//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditID { get; set; }
        public System.DateTime DateDone { get; set; }
        public string TypeTran { get; set; }
        public string TableAff { get; set; }
        public int SYSUserProfileID { get; set; }
    
        public virtual SYSUserProfile SYSUserProfile { get; set; }
    }
}
