//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMessage
    {
        public int MessID { get; set; }
        [Required(ErrorMessage = "You cannot send a blank notification")]
        [Display(Name = "Notification")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 20)]

        public string Msg { get; set; }
        public System.TimeSpan TimeMes { get; set; }
        public int NumberMess { get; set; }
        public Nullable<int> VolunteerID { get; set; }
        public Nullable<int> SYSUserProfileID { get; set; }
    
        public virtual SYSUserProfile SYSUserProfile { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
