//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EventMessage
    {
        public int MessID { get; set; }
        public string Msg { get; set; }
        public System.TimeSpan TimeMes { get; set; }
        public int NumberMess { get; set; }
        public Nullable<int> VolunteerID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SYSUserProfileID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual SYSUserProfile SYSUserProfile { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
