//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FunctionEvent()
        {
            this.Attendances = new HashSet<Attendance>();
            this.RSVP_Event = new HashSet<RSVP_Event>();
            this.TRWLASchedules = new HashSet<TRWLASchedule>();
        }
    
        public int FunctionID { get; set; }
        public string Function_Name { get; set; }
        public string Function_Summary { get; set; }
        public string Function_Description { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}", ApplyFormatInEditMode = true)]

        public System.DateTime Function_Date { get; set; }
        public System.TimeSpan Function_StartTime { get; set; }
        public System.TimeSpan Function_EndTime { get; set; }
        public string Function_Theme { get; set; }
        public Nullable<int> GuestSpeakerID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public int Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual GuestSpeaker GuestSpeaker { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSVP_Event> RSVP_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRWLASchedule> TRWLASchedules { get; set; }
    }
}
