//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecture()
        {
            this.Attendances = new HashSet<Attendance>();
            this.LectureReviews = new HashSet<LectureReview>();
            this.RSVP_Event = new HashSet<RSVP_Event>();
            this.TRWLASchedules = new HashSet<TRWLASchedule>();
        }
    
        public int LectureID { get; set; }
        [Required]
        [StringLength(35, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Lecture_Name")]
        public string Lecture_Name { get; set; }
        [Required]
        [StringLength(35, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Lecture_Summary")]
        public string Lecture_Summary { get; set; }
        [Required]
        [StringLength(35, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Lecture_Description")]
        public string Lecture_Description { get; set; }
        [Required]
        public System.DateTime Lecture_Date { get; set; }
        [Required]
        public System.TimeSpan Lecture_StartTime { get; set; }
        [Required]
        public System.TimeSpan Lecture_EndTime { get; set; }
        [Required]
        [StringLength(35, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Lecture_Theme")]
        public string Lecture_Theme { get; set; }
        [Required]
        public Nullable<int> VenueID { get; set; }
        [Required]
        public Nullable<int> ResidenceID { get; set; }
        [Required]
        public Nullable<int> ContentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Content Content { get; set; }
        public virtual Residence Residence { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureReview> LectureReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSVP_Event> RSVP_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRWLASchedule> TRWLASchedules { get; set; }
    }
}
