//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterData
    {
        public int MasterID { get; set; }
        public int LecAttend { get; set; }
        public int FuncAttend { get; set; }
        public int ComAttend { get; set; }
        public int GenAttend { get; set; }
        public System.DateTime RegDate { get; set; }
        public int LogAttendTime { get; set; }
        public int CancelEvent { get; set; }
    }
}
