//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class progressbar
    {
        public int ProgBarID { get; set; }
        public int SYSUserProfileID { get; set; }
        public int LecProg { get; set; }
        public int FuncProg { get; set; }
        public int ComProg { get; set; }
        public int GenProg { get; set; }
    
        public virtual SYSUserProfile SYSUserProfile { get; set; }
    }
}
