//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class RSVPSchedule
    {
        public int RsvpScheduleID { get; set; }
        public int rsvpID { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<int> SYSUserProfileID { get; set; }
    
        public virtual RSVP_Event RSVP_Event { get; set; }
        public virtual TRWLASchedule TRWLASchedule { get; set; }
        public virtual SYSUserProfile SYSUserProfile { get; set; }
    }
}
