//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqueCode
    {
        public int UniID { get; set; }
        [Required(ErrorMessage = "A unique code is required")]
        [Display(Name = "Unique Code")]
        public int Code { get; set; }
        public System.DateTime stamptime { get; set; }
    }
}
