//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerFeedback
    {
        public int VolunteerFeedbackID { get; set; }
        public System.DateTime Feedback_Date { get; set; }
        public int Enjoyment { get; set; }
        public int Preparation { get; set; }
        public int Expectation { get; set; }
        public int Communication { get; set; }
        public int Growth { get; set; }
        public int Impact { get; set; }
        public int Coping { get; set; }
        public int FutureVision { get; set; }
        public int Confident { get; set; }
        public int Challenge { get; set; }
        public string Improvement { get; set; }
        public string Criticism { get; set; }
        public string FutureMonths { get; set; }
        public string ExperienceImpact { get; set; }
    }
}
